#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
cleanCase
rm flat_plate_lowvis.foam

# this was the original allclean script for icofoam cases
# keepCases="cavity cavityGrade cavityClipped"
# loseCases="cavityFine cavityHighRe"

# for caseName in $keepCases
# do
# (
#     cd $caseName || exit
#     foamCleanTutorials
# )
# done

# for caseName in $loseCases
# do
#     removeCase $caseName
# done

#------------------------------------------------------------------------------

